name: Attach binaries to release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run tsc
      - run: npm run download
      - run: npm run build

# windows zip with chrome
      - run: mkdir -p windows/.local-chromium/win64-869685
      - run: cp build/japdl-win.exe windows
      - run: cp -r .local-chromium/win64-869685 windows/.local-chromium/

      - name: zip windows files (chrome)
        uses: papeloto/action-zip@v1
        with:
            files: windows
            dest: japdl-windows.zip

# windows zip without chrome
      - name: zip windows files (no chrome)
      - run: "cp config_windows.txt config.txt"
        uses: papeloto/action-zip@v1
        with:
            files: build/japdl-win.exe config.txt
            dest: japdl-windows-no-chrome.zip


# linux zip with chrome
      - run: mkdir -p linux/.local-chromium/linux-869685
      - run: cp build/japdl-linux linux
      - run: cp -r .local-chromium/linux-869685 linux/.local-chromium/
      - run: chmod 777 linux/.local-chromium/linux-869685/chrome-linux/chrome

      - name: zip linux files (chrome)
        uses: papeloto/action-zip@v1
        with:
            files: linux
            dest: japdl-linux.zip

# linux zip without chrome
      - name: zip linux files (no chrome)
      - run: "cp config_linux.txt config.txt"
        uses: papeloto/action-zip@v1
        with:
            files: build/japl-linux
            dest: japdl-linux-no-chrome.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            japdl-windows.zip
            japdl-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}