name: Attach binaries to release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run tsc
      - run: npm run download
      - run: npm run build

      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: ".local-chromium/"
          target: "build/"
          flags: "-r"

      - name: zip windows files
        uses: papeloto/action-zip@v1
        with:
            files: [build/japdl-win.exe, .local-chromium/win64-869685]
            dest: japdl-exe.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: japdl-exe.zip
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}