name: Attach binaries to release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run tsc
      - run: npm run download
      - run: npm run build

      - run: mkdir -p windows/.local-chromium/win64-869685
      - run: cp build/japdl-win.exe windows
      - run: cp -r .local-chromium/win64-869685 windows/.local-chromium/

      - name: zip windows files
        uses: papeloto/action-zip@v1
        with:
            files: windows
            dest: japdl-windows.zip

      - run: mkdir -p linux/.local-chromium/linux-869685
      - run: cp build/japdl-linux linux
      - run: cp -r .local-chromium/linux-869685 linux/.local-chromium/

      - name: zip linux files
        uses: papeloto/action-zip@v1
        with:
            files: linux
            dest: japdl-linux.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: japdl-windows.zip japdl-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}