name: Attach binaries to release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install and compile
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
        - run: npm ci
        - run: npm run tsc
        - run: npm test
        - run: npm run build
      - name: zip files
        with:
            files: build/
            dest: japdl.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: japdl.zip
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}